# Generated by Django 4.2.1 on 2023-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('organisation', 'Organisation'), ('charity', 'Charity'), ('government', 'Government')], default='individual', max_length=50),
        ),
    ]
