# Generated by Django 4.2.1 on 2023-06-28 10:08

import core.models.userModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_order_orderhistory_orderitem_product_productrating_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.userModels.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='statistics',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statistics',
            field=models.ManyToManyField(related_name='users', to='core.userstatistics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='testpassword', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission'),
        ),
    ]
